[project]
name = "fastapi-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.10"
dependencies = [
    "bson>=0.5.10",
    "fastapi>=0.115.12",
    "pymongo==4.12.1",
    "uvicorn>=0.34.3",
]
